### ISSUE TITLE
InvalidArgumentError (see above for traceback): Incompatible shapes: [99,512,28,28] vs. [99,28,28,512]

### ISSUE THREAD

**Issue by molefeskymleya** [griffbr/BubbleNets#4]
hello there.

I am extremely interested in your work, I watched the youtube videos and read the paper. Now, I want to reproduce this masterpiece on my end. 

I ran `python bubblenets_select_frame.py` and got the error mentioned above... what could be the cause of this? How can I fix it?

The full error message is as follows:
`[root@~ BubbleNets-master]# python bubblenets_select_frame.py
ResNet preprocessing for soapbox
WARNING:tensorflow:From /home/BubbleNets-master/methods/annotate_suggest/ResNet/resnet_v2.py:204: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-09-27 07:21:25.503906: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [99,512,28,28] vs. [99,28,28,512]
         [[Node: resnet_v2_50/block2/unit_3/bottleneck_v2/add = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet_v2_50/block2/unit_2/bottleneck_v2/add, resnet_v2_50/block2/unit_3/bottleneck_v2/conv3/BiasAdd)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bubblenets_select_frame.py", line 125, in <module>
    main()
  File "bubblenets_select_frame.py", line 108, in main
    resnet_process_data_dir(rawDataDir)
  File "/home/BubbleNets-master/methods/annotate_suggest/ResNet_preprocess.py", line 56, in resnet_process_data_dir
    np_images, resnet_vectors = sess.run([processed_images, logits])
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [99,512,28,28] vs. [99,28,28,512]
         [[Node: resnet_v2_50/block2/unit_3/bottleneck_v2/add = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet_v2_50/block2/unit_2/bottleneck_v2/add, resnet_v2_50/block2/unit_3/bottleneck_v2/conv3/BiasAdd)]]

Caused by op 'resnet_v2_50/block2/unit_3/bottleneck_v2/add', defined at:
  File "bubblenets_select_frame.py", line 125, in <module>
    main()
  File "bubblenets_select_frame.py", line 108, in main
    resnet_process_data_dir(rawDataDir)
  File "/home/BubbleNets-master/methods/annotate_suggest/ResNet_preprocess.py", line 49, in resnet_process_data_dir
    num_classes=None, is_training=False)
  File "/home/BubbleNets-master/methods/annotate_suggest/ResNet/resnet_v2.py", line 265, in resnet_v2_50
    scope=scope)
  File "/home/BubbleNets-master/methods/annotate_suggest/ResNet/resnet_v2.py", line 196, in resnet_v2
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 215, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/BubbleNets-master/methods/annotate_suggest/ResNet/resnet_v2.py", line 112, in bottleneck
    output = shortcut + residual
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 907, in binary_op_wrapper
    return func(x, y, name=name)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 183, in add
    "Add", x=x, y=y, name=name)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [99,512,28,28] vs. [99,28,28,512]
         [[Node: resnet_v2_50/block2/unit_3/bottleneck_v2/add = Add[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](resnet_v2_50/block2/unit_2/bottleneck_v2/add, resnet_v2_50/block2/unit_3/bottleneck_v2/conv3/BiasAdd)]]
`

**Comment by griffbr** [comment]
Hello molefeskymleya,

Thank you for your kind words! It appears that you are running into an issue when generating the ResNet vectors for each video frame. For some reason, I believe when the residual is being added for the output in ResNet, the dimensions of the Tensors are inconsistent ("[99,512,28,28] vs. [99,28,28,512]"). I have not been able to replicate your error; I've even tried running Tensorflow using GPU and CPU (like you). One reason for this difference could be that your environment is using Python 3.6 while mine is using Python 2.7. 

The easiest solution might be for you to change the shape of the Tensors being added together at "'/home/BubbleNets-master/methods/annotate_suggest/ResNet/resnet_v2.py', line 112" to make them consistent (e.g., https://stackoverflow.com/questions/38212205/how-do-i-swap-tensors-axes-in-tensorflow).

Alternatively, if it is easy for you to try running from an environment that uses Python 2.7, this may solve this problem as well.
